service: auction-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          method: GET
          path: /hello

plugins:
  - serverless-esbuild
